#!/usr/bin/env python3
"""
Kamui CLI entry point. See python/kamui/README.md for details.
"""

# Import Block

## Standard Python imports
import os, sys

## Kamui modules
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "python")) # Lets kamui work from anywhere.
from kamui.cli import main

sys.exit(main())
