"""
Local HTCondor backend (LPC).

Use it when you want tight control or fast turnaround on a handful of files:
debugging a new content preset, running over a private dataset that CRAB is
awkward about, or reprocessing files already staged on our EOS. Input is read
over xrootd and the ntuple is copied back to EOS with xrdcp.

Trade-off vs CRAB: no automatic retries, and jobs run at FNAL regardless of
where the data lives, so datasets not cached here will read slowly.
"""

import json
import os
import stat
import subprocess

from ..configReaders.sites import loadSites
from .common import chunk, outputPath, taskDir, writeResolvedContent, writeTaskRecord
from ..foundations import paths

RUN_SCRIPT = r'''#!/bin/bash
# Generated by kamui. $1 = sample name, $2 = job index
set -e
SAMPLE=$1
IDX=$2
echo "[job] sample=$SAMPLE index=$IDX host=$(hostname) start=$(date)"

export SCRAM_ARCH={scramArch}
source /cvmfs/cms.cern.ch/cmsset_default.sh
scramv1 project CMSSW {cmsswVersion} > /dev/null
cd {cmsswVersion}/src
eval `scramv1 runtime -sh`
cd $_CONDOR_SCRATCH_DIR

python3 - "$SAMPLE" "$IDX" <<'PY'
import json, sys
sample, idx = sys.argv[1], sys.argv[2]
files = json.load(open("fileLists.json"))[sample][int(idx)]
open("inputs.txt", "w").write(",".join(files))
PY
INPUTS=$(cat inputs.txt)

cmsRun kamuiNtuple_cfg.py content={contentJson} isMC={isMC} output={output} \
    inputFiles=$INPUTS outputFile=out.root miniaodFile=slim.root maxEvents={maxEvents}

xrdfs {eosRedirector} mkdir -p {outDir}
for F in out.root:ntuple slim.root:miniaod; do
  SRC=${{F%%:*}}; TAG=${{F##*:}}
  [ -f "$SRC" ] || continue
  DEST={eosRedirector}/{outDir}/${{SAMPLE}}_${{TAG}}_${{IDX}}.root
  xrdcp -f "$SRC" "$DEST"
  echo "[job] wrote $DEST"
done
echo "[job] end=$(date)"
'''

JDL = '''# Generated by kamui - resubmit with: condor_submit {jdlName}
universe                = vanilla
executable              = runJob.sh
arguments               = $(sample) $(index)
transfer_input_files    = {inputFiles}
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
output                  = logs/$(sample)_$(index).out
error                   = logs/$(sample)_$(index).err
log                     = logs/condor.log
request_memory          = {memoryMB}
request_disk            = {diskMB}
# LPC worker OS selection. If jobs sit idle forever, try +REQUIRED_OS = "rhel9" instead.
+DesiredOS              = "EL9"
x509userproxy           = $ENV(X509_USER_PROXY)

queue sample,index from jobList.txt
'''


def prepare(samples, taskName, fileLists, sites=None, filesPerJob=5,
            maxEvents=-1, memoryMB=2500, diskMB=4000000, output="ntuple",
            cmsswVersion=None, scramArch=None):
    """
    Write a complete condor submission area.

    fileLists: {sampleName: [lfn, ...]} - resolved by the caller (from DAS or EOS),
    so this function never touches the network.
    """
    sites = sites or loadSites()
    # The release lives in config/sites.json so bumping it is a config change.
    cmsswVersion = cmsswVersion or sites["cmssw"]["version"]
    scramArch = scramArch or sites["cmssw"]["scramArch"]
    d = taskDir(taskName)
    os.makedirs(os.path.join(d, "logs"), exist_ok=True)

    contentCache = {}
    chunked, jobRows = {}, []
    for s in samples:
        lfns = fileLists.get(s["name"], [])
        if not lfns:
            continue
        key = (s["content"], bool(s["isMC"]))
        if key not in contentCache:
            contentCache[key] = writeResolvedContent(d, s["content"], bool(s["isMC"]))
        groups = chunk(lfns, int(s.get("unitsPerJob") or filesPerJob))
        chunked[s["name"]] = [[sites["sourceRedirector"].rstrip("/") + "/" + f if not f.startswith("root:") else f
                               for f in g] for g in groups]
        jobRows += [f"{s['name']},{i}" for i in range(len(groups))]

    with open(os.path.join(d, "fileLists.json"), "w") as f:
        json.dump(chunked, f, indent=1)
    with open(os.path.join(d, "jobList.txt"), "w") as f:
        f.write("\n".join(jobRows) + "\n")

    # One run script per (content, isMC) combination would be cleaner, but in
    # practice a task mixes at most a couple; write one per combination.
    scripts = []
    for (preset, isMC), contentJson in contentCache.items():
        script = RUN_SCRIPT.format(
            scramArch=scramArch,
            cmsswVersion=cmsswVersion,
            contentJson=os.path.basename(contentJson),
            isMC="True" if isMC else "False",
            maxEvents=maxEvents,
            output=output,
            eosRedirector=sites["eosRedirector"].rstrip("/"),
            outDir="/".join([sites["stageoutBase"].rstrip("/"), "ntuples", taskName, "$SAMPLE"]),
        )
        p = os.path.join(d, "runJob.sh")
        with open(p, "w") as f:
            f.write(script)
        os.chmod(p, os.stat(p).st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)
        scripts.append(p)

    inputFiles = ["fileLists.json", os.path.join(paths.CMSSW_DIR, "kamuiNtuple_cfg.py"),
                  os.path.join(paths.CMSSW_DIR, "kamuiTables.py")] + list(contentCache.values())
    jdlName = "submit.jdl"
    with open(os.path.join(d, jdlName), "w") as f:
        f.write(JDL.format(jdlName=jdlName, inputFiles=",".join(inputFiles),
                           memoryMB=memoryMB, diskMB=diskMB))

    writeTaskRecord(d, {
        "task": taskName, "backend": "condor", "output": output, "nJobs": len(jobRows),
        "samples": sorted(chunked), "filesPerJob": filesPerJob,
        "outDirBase": "/".join([sites["stageoutBase"].rstrip("/"), "ntuples", taskName]),
    })
    return d, len(jobRows)


def submit(taskName, dryRun=False):
    d = taskDir(taskName, create=False)
    jdl = os.path.join(d, "submit.jdl")
    if dryRun:
        print(f"  [dry-run] condor_submit {jdl}")
        return 0
    r = subprocess.run(["condor_submit", "submit.jdl"], cwd=d, capture_output=True, text=True)
    print(r.stdout.strip() or r.stderr.strip())
    return r.returncode
