"""
Local HTCondor backend for LPC.
"""

# Import Block

## Standard Python imports
import datetime
import json
import os
import re
import stat
import subprocess

## Kamui modules
from ..configReaders.sites import loadSites
from .common import chunk, contentStem, outputBase, publishRecord, resolveTaskDir, runTool, taskDir, writeResolvedContent, writeTaskRecord
from ..foundations import paths

## Input files per job when neither the flag nor the sample says otherwise
DEFAULT_FILES_PER_JOB = 5

RUN_SCRIPT = r'''#!/bin/bash
# Generated by kamui. $1 = sample name, $2 = job index
set -e
SAMPLE=$1
IDX=$2
echo "[job] sample=$SAMPLE index=$IDX host=$(hostname) start=$(date)"

export SCRAM_ARCH={scramArch}
source /cvmfs/cms.cern.ch/cmsset_default.sh
scramv1 project CMSSW {cmsswVersion} > /dev/null
cd {cmsswVersion}/src
eval `scramv1 runtime -sh`
cd $_CONDOR_SCRATCH_DIR

python3 - "$SAMPLE" "$IDX" <<'PY'
import json, sys
sample, idx = sys.argv[1], sys.argv[2]
files = json.load(open("fileLists.json"))[sample][int(idx)]
open("inputs.txt", "w").write(",".join(files))
PY
INPUTS=$(cat inputs.txt)

cmsRun kamuiNtuple_cfg.py content={contentJson} isMC={isMC} output={output} \
    inputFiles=$INPUTS outputFile=out.root miniaodFile=slim.root maxEvents={maxEvents}

xrdfs {eosRedirector} mkdir -p {outDir}
for F in out.root:ntuple slim.root:miniaod; do
  SRC=${{F%%:*}}; TAG=${{F##*:}}
  [ -f "$SRC" ] || continue
  DEST={eosRedirector}/{outDir}/${{SAMPLE}}_${{TAG}}_${{IDX}}.root
  xrdcp -f "$SRC" "$DEST"
  echo "[job] wrote $DEST"
done
echo "[job] end=$(date)"
'''

JDL = '''# Generated by kamui - resubmit with: condor_submit {jdlName}
universe                = vanilla
executable              = $(script)
arguments               = $(sample) $(index)
transfer_input_files    = {inputFiles}
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
output                  = {logDir}/$(sample)_$(index).out
error                   = {logDir}/$(sample)_$(index).err
log                     = {logDir}/condor.log
request_memory          = {memoryMB}
request_disk            = {diskMB}
# LPC worker OS selection. If jobs sit idle forever, try +REQUIRED_OS = "rhel9" instead.
+DesiredOS              = "EL9"
x509userproxy           = $ENV(X509_USER_PROXY)

queue sample,index,script from {jobListName}
'''


def _scriptName(presetName, isMC, era):
    """One run script per content preset, data/MC flavour and era, since each combination gets its own resolved content."""
    return f"runJob_{contentStem(presetName)}_{'mc' if isMC else 'data'}_{era}.sh"


# fileLists maps a sample name to the list of LFNs it should run over, resolved by the caller from DAS or EOS.
def prepare(samples, taskName, fileLists, sites=None, filesPerJob=None, maxEvents=-1, memoryMB=2500, diskMB=4000000, output="ntuple", cmsswVersion=None, scramArch=None, assumeYes=False, base=None):
    """Write a complete condor submission area. Returns the directory, the job count and the task name used."""
    sites = sites or loadSites()
    base = outputBase(sites, "condor", base)
    # The release lives in config/sites.json
    cmsswVersion = cmsswVersion or sites["cmssw"]["version"]
    scramArch = scramArch or sites["cmssw"]["scramArch"]
    d, taskName = resolveTaskDir(taskName, assumeYes)
    os.makedirs(os.path.join(d, "logs"), exist_ok=True)

    contentCache = {}
    chunked, jobRows = {}, []
    effective = {}
    dropped = []
    for s in samples:
        lfns = fileLists.get(s["name"], [])
        if len(set(lfns)) != len(lfns):
            print(f"  warning: {s['name']} listed {len(lfns) - len(set(lfns))} duplicate file(s); keeping one copy of each")
            lfns = sorted(set(lfns))
        if not lfns:
            dropped.append(s["name"])
            continue
        key = (s["content"], bool(s["isMC"]), s["era"])
        if key not in contentCache:
            contentCache[key] = writeResolvedContent(d, s["content"], bool(s["isMC"]), s["era"])
        perJob = int(filesPerJob or s.get("unitsPerJob") or DEFAULT_FILES_PER_JOB)
        effective[s["name"]] = perJob
        groups = chunk(lfns, perJob)
        chunked[s["name"]] = [[sites["sourceRedirector"].rstrip("/") + "/" + f if not f.startswith("root:") else f
                               for f in g] for g in groups]
        jobRows += [f"{s['name']},{i},{_scriptName(*key)}" for i in range(len(groups))]

    if dropped:
        print(f"  warning: no input files found, so {len(dropped)} sample(s) got no jobs: {', '.join(dropped)}")

    with open(os.path.join(d, "fileLists.json"), "w") as f:
        json.dump(chunked, f, indent=1)
    with open(os.path.join(d, "jobList.txt"), "w") as f:
        f.write("\n".join(jobRows) + "\n")

    # A task may mix content presets and MC with data, so each combination gets its own run script and the job rows name the one they need.
    for (preset, isMC, era), contentJson in contentCache.items():
        script = RUN_SCRIPT.format(
            scramArch=scramArch,
            cmsswVersion=cmsswVersion,
            contentJson=os.path.basename(contentJson),
            isMC="True" if isMC else "False",
            maxEvents=maxEvents,
            output=output,
            eosRedirector=sites["eosRedirector"].rstrip("/"),
            outDir="/".join([base, "ntuples", taskName, "$SAMPLE"]),
        )
        p = os.path.join(d, _scriptName(preset, isMC, era))
        with open(p, "w") as f:
            f.write(script)
        os.chmod(p, os.stat(p).st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)

    inputFiles = ["fileLists.json", os.path.join(paths.CMSSW_DIR, "kamuiNtuple_cfg.py"),
                  os.path.join(paths.CMSSW_DIR, "kamuiTables.py")] + list(contentCache.values())
    jdlName = "submit.jdl"
    with open(os.path.join(d, jdlName), "w") as f:
        f.write(JDL.format(jdlName=jdlName, inputFiles=",".join(inputFiles),
                           memoryMB=memoryMB, diskMB=diskMB,
                           logDir="logs", jobListName="jobList.txt"))

    submitted = [s for s in samples if s["name"] in chunked]
    writeTaskRecord(d, {
        "task": taskName, "backend": "condor", "output": output, "nJobs": len(jobRows),
        "samples": sorted(chunked), "droppedSamples": sorted(dropped), "filesPerJob": effective,
        "maxEvents": maxEvents, "memoryMB": memoryMB,
        "nInputFiles": {k: sum(len(g) for g in v) for k, v in sorted(chunked.items())},
        "outDirBase": "/".join([base, "ntuples", taskName]),
    }, samples=submitted, sites=sites, resolvedContent=contentCache.values())
    return d, len(jobRows), taskName, base


def submit(taskName, dryRun=False, base=None):
    """Run `condor_submit` on the task's JDL."""
    d = taskDir(taskName, create=False)
    jdl = os.path.join(d, "submit.jdl")
    if dryRun:
        print(f"  [dry-run] condor_submit {jdl}")
        return 0
    r = runTool(["condor_submit", "submit.jdl"], cwd=d, capture_output=True, text=True)
    print(r.stdout.strip() or r.stderr.strip())
    if r.returncode == 0:
        # condor_submit reports "N job(s) submitted to cluster 12345." - keep the id so status can ask about this task alone.
        cluster = re.search(r"submitted to cluster (\d+)", r.stdout)
        # LPC spreads a submission over several schedds, and condor_q asks the default one unless told otherwise.
        schedd = re.search(r"submit jobs to (\S+)", r.stdout)
        if cluster or schedd:
            recordPath = os.path.join(d, "task.json")
            with open(recordPath) as f:
                rec = json.load(f)
            if cluster:
                rec["condorCluster"] = int(cluster.group(1))
            if schedd:
                rec["schedd"] = schedd.group(1)
            tmp = recordPath + ".tmp"           # Same temp-and-rename as writeTaskRecord, so a failure here cannot destroy the record.
            with open(tmp, "w") as f:
                json.dump(rec, f, indent=2)
            os.replace(tmp, recordPath)
        publishRecord(d, loadSites(), taskName, base)
    return r.returncode


# What a finished job leaves on EOS. The run script names outputs <sample>_<tag>_<index>.root, so a job
# that died anywhere before the copy leaves nothing, and a job that ran twice leaves the same name twice.
def _expectedOutputs(sampleName, index, output):
    tags = ["ntuple", "miniaod"] if output == "both" else [output]
    return [f"{sampleName}_{tag}_{index}.root" for tag in tags]


def _eosListing(redirector, directory):
    """Basenames present in an EOS directory, empty if it does not exist yet."""
    try:
        r = subprocess.run(["xrdfs", redirector, "ls", directory], capture_output=True, text=True, timeout=300)
    except (OSError, subprocess.SubprocessError) as e:
        raise RuntimeError(f"could not list {directory}: {e}")
    if r.returncode != 0:
        return set()
    return {os.path.basename(line) for line in r.stdout.split() if line.strip()}


def missingJobs(taskName, sites=None):
    """Job rows from the task whose outputs are not on EOS. Returns (rows, presentCount, expectedCount)."""
    sites = sites or loadSites()
    d = taskDir(taskName, create=False)
    with open(os.path.join(d, "task.json")) as f:
        info = json.load(f)
    if info.get("backend") != "condor":
        raise ValueError(f"task '{taskName}' ran on {info.get('backend')}, not condor")
    outDirBase = info.get("outDirBase")
    if not outDirBase:
        raise ValueError(f"task '{taskName}' has no outDirBase recorded, so its outputs cannot be located")
    output = info.get("output", "ntuple")
    redirector = sites["eosRedirector"].rstrip("/")

    rows = [line.strip() for line in open(os.path.join(d, "jobList.txt")) if line.strip()]
    listings, missing, nPresent, nExpected = {}, [], 0, 0
    for row in rows:
        sampleName, index = row.split(",")[0], row.split(",")[1]
        if sampleName not in listings:
            listings[sampleName] = _eosListing(redirector, f"{outDirBase}/{sampleName}")
        wanted = _expectedOutputs(sampleName, index, output)
        nExpected += len(wanted)
        here = [w for w in wanted if w in listings[sampleName]]
        nPresent += len(here)
        if len(here) != len(wanted):
            missing.append(row)
    return missing, nPresent, nExpected


def _nextRetry(d):
    """The first retry number not already used, so an earlier attempt's logs are never overwritten."""
    n = 1
    while os.path.exists(os.path.join(d, "logs", f"retry{n}")) or os.path.exists(os.path.join(d, f"jobList.retry{n}.txt")):
        n += 1
    return n


# Resubmission reuses the task area untouched: the same run scripts, the same resolved content and the same
# EOS destination, so retried outputs land beside the ones that already succeeded. Only the job list and the
# log directory are new.
def resubmit(taskName, dryRun=False, sites=None, rows=None):
    """Submit only the jobs of a task whose outputs are missing. Returns (retryNumber, nJobs, returncode)."""
    sites = sites or loadSites()
    d = taskDir(taskName, create=False)
    if rows is None:
        rows = missingJobs(taskName, sites)[0]
    if not rows:
        return None, 0, 0

    n = _nextRetry(d)
    logDir = os.path.join("logs", f"retry{n}")
    jobListName = f"jobList.retry{n}.txt"
    if dryRun:
        # Writing nothing here keeps the retry number free, so a dry run does not push the real attempt to retry2.
        print(f"  [dry-run] condor_submit submit.retry{n}.jdl   ({len(rows)} job(s), logs would go to {logDir})")
        return n, len(rows), 0

    os.makedirs(os.path.join(d, logDir), exist_ok=True)
    with open(os.path.join(d, jobListName), "w") as f:
        f.write("\n".join(rows) + "\n")

    with open(os.path.join(d, "submit.jdl")) as f:
        original = f.read()
    jdlName = f"submit.retry{n}.jdl"
    jdl = original.replace("queue sample,index,script from jobList.txt",
                           f"queue sample,index,script from {jobListName}")
    jdl = jdl.replace("output                  = logs/$(sample)_$(index).out",
                      f"output                  = {logDir}/$(sample)_$(index).out")
    jdl = jdl.replace("error                   = logs/$(sample)_$(index).err",
                      f"error                   = {logDir}/$(sample)_$(index).err")
    jdl = jdl.replace("log                     = logs/condor.log",
                      f"log                     = {logDir}/condor.log")
    jdl = jdl.replace("# Generated by kamui - resubmit with: condor_submit submit.jdl",
                      f"# Generated by kamui - retry {n} of task {taskName}. Resubmit with: condor_submit {jdlName}")
    if f"from {jobListName}" not in jdl or logDir not in jdl:
        raise ValueError(f"could not build a retry JDL from {os.path.join(d, 'submit.jdl')}; its format has changed")
    with open(os.path.join(d, jdlName), "w") as f:
        f.write(jdl)

    r = runTool(["condor_submit", jdlName], cwd=d, capture_output=True, text=True)
    print(r.stdout.strip() or r.stderr.strip())
    if r.returncode == 0:
        _recordRetry(d, n, len(rows), logDir, jdlName, r.stdout)
    return n, len(rows), r.returncode


def _recordRetry(d, n, nJobs, logDir, jdlName, stdout):
    """Append the retry to task.json without disturbing the original submission's record."""
    recordPath = os.path.join(d, "task.json")
    with open(recordPath) as f:
        rec = json.load(f)
    entry = {
        "retry": n,
        "nJobs": nJobs,
        "logDir": logDir,
        "jdl": jdlName,
        "submittedAt": datetime.datetime.now().astimezone().isoformat(timespec="seconds"),
    }
    m = re.search(r"submitted to cluster (\d+)", stdout or "")
    if m:
        entry["condorCluster"] = int(m.group(1))
    m = re.search(r"submit jobs to (\S+)", stdout or "")
    if m:
        entry["schedd"] = m.group(1)
    rec.setdefault("retries", []).append(entry)
    tmp = recordPath + ".tmp"
    with open(tmp, "w") as f:
        json.dump(rec, f, indent=2)
    os.replace(tmp, recordPath)
