"""
CRAB3 backend, the default. One CRAB task per sample.
"""

# Import Block

## Standard Python imports
import os
import subprocess

## Kamui modules
from ..configReaders.sites import loadSites
from .common import checkTaskName, outputBase, publishRecord, resolveTaskDir, taskDir, writeResolvedContent, writeTaskRecord
from ..foundations import paths

## Input files per job when neither the flag nor the sample says otherwise
DEFAULT_FILES_PER_JOB = 5

CRAB_TEMPLATE = '''# Generated by kamui - edit the config JSONs, not this file.
# Sample : {sampleName}
# Dataset: {dataset}
from CRABClient.UserUtilities import config
config = config()

config.General.requestName     = {requestName!r}
config.General.workArea        = {workArea!r}
config.General.transferOutputs = True
config.General.transferLogs    = False

config.JobType.pluginName  = 'Analysis'
config.JobType.psetName    = {psetName!r}
config.JobType.pyCfgParams = {pyCfgParams!r}
config.JobType.inputFiles  = {inputFiles!r}
config.JobType.maxMemoryMB = {maxMemoryMB}
config.JobType.numCores    = 1

config.Data.inputDataset     = {dataset!r}
config.Data.inputDBS         = {inputDBS!r}
config.Data.splitting        = 'FileBased'
config.Data.unitsPerJob      = {unitsPerJob}
config.Data.outLFNDirBase    = {outLFNDirBase!r}
config.Data.publication      = False
config.Data.outputDatasetTag = {outputDatasetTag!r}
{lumiMaskLine}
config.Site.storageSite = {storageSite!r}
'''


def _requestName(taskName, sampleName):
    # CRAB caps requestName at 100 characters.
    name = f"{taskName}__{sampleName}"
    return name[:100]


def _checkRequestNames(taskName, samples):
    seen = {}
    for s in samples:
        r = _requestName(taskName, s["name"])
        if r in seen:
            raise ValueError(
                f"task name '{taskName}' is too long: samples '{seen[r]}' and '{s['name']}' "
                f"both truncate to the same CRAB requestName. Use a shorter --task."
            )
        seen[r] = s["name"]


def prepare(samples, taskName, sites=None, unitsPerJob=None, maxMemoryMB=2500, output="ntuple", assumeYes=False, base=None):
    """Write one crabConfig per sample into the task directory. Returns their paths and the task name used."""
    sites = sites or loadSites()
    checkTaskName(taskName)
    _checkRequestNames(taskName, samples)
    base = outputBase(sites, "crab", base)
    d, taskName = resolveTaskDir(taskName, assumeYes)
    _checkRequestNames(taskName, samples)
    pset = os.path.join(paths.CMSSW_DIR, "kamuiNtuple_cfg.py")

    contentCache = {}
    effective = {s["name"]: int(unitsPerJob or s.get("unitsPerJob") or DEFAULT_FILES_PER_JOB) for s in samples}
    written = []
    for s in samples:
        key = (s["content"], bool(s["isMC"]))
        if key not in contentCache:
            contentCache[key] = writeResolvedContent(d, s["content"], bool(s["isMC"]))
        contentJson = contentCache[key]

        inputDBS = "phys03" if "phys03" in s["dasInstance"] else "global"
        lumiMaskLine = f"config.Data.lumiMask = {s['lumiMask']!r}\n" if s.get("lumiMask") else ""

        text = CRAB_TEMPLATE.format(
            sampleName=s["name"],
            dataset=s["dataset"],
            requestName=_requestName(taskName, s["name"]),
            workArea=os.path.join(d, "crab"),
            psetName=pset,
            pyCfgParams=[
                f"content={contentJson}",
                f"isMC={'True' if s['isMC'] else 'False'}",
                f"output={output}",
            ],
            inputFiles=[contentJson, os.path.join(paths.CMSSW_DIR, "kamuiTables.py")],
            maxMemoryMB=maxMemoryMB,
            inputDBS=inputDBS,
            unitsPerJob=effective[s["name"]],
            outLFNDirBase="/".join([base, "ntuples", taskName]),
            outputDatasetTag=s["name"][:99],
            lumiMaskLine=lumiMaskLine,
            storageSite=sites["crabStorageSite"],
        )
        path = os.path.join(d, f"crabConfig_{s['name']}.py")
        with open(path, "w") as f:
            f.write(text)
        written.append(path)

    writeTaskRecord(d, {
        "task": taskName, "backend": "crab", "output": output, "nSamples": len(samples),
        "samples": [s["name"] for s in samples],
        "content": sorted({s["content"] for s in samples}),
        "unitsPerJob": effective, "maxMemoryMB": maxMemoryMB,
        "outLFNDirBase": "/".join([base, "ntuples", taskName]),
    }, samples=samples, sites=sites, resolvedContent=contentCache.values())
    return written, taskName, base


def submit(configPaths, dryRun=False, sites=None, taskName=None, base=None):
    """Run `crab submit` for each generated config."""
    ok, bad = [], []
    for p in configPaths:
        if dryRun:
            print(f"  [dry-run] crab submit -c {p}")
            ok.append(p)
            continue
        r = subprocess.run(["crab", "submit", "-c", p], capture_output=True, text=True)
        if r.returncode != 0:
            print(f"  FAILED {os.path.basename(p)}: {r.stderr.strip().splitlines()[-1:] or r.stdout[-400:]}")
            bad.append(p)
        else:
            print(f"  submitted {os.path.basename(p)}")
            ok.append(p)
    if ok and not dryRun and taskName:
        publishRecord(taskDir(taskName, create=False), sites or loadSites(), taskName, base)
    return ok, bad


def status(taskName):
    """`crab status` over every crab project in a task directory."""
    workArea = os.path.join(taskDir(taskName, create=False), "crab")
    if not os.path.isdir(workArea):
        raise FileNotFoundError(f"no crab work area at {workArea}")
    for proj in sorted(os.listdir(workArea)):
        full = os.path.join(workArea, proj)
        if not os.path.isdir(full):
            continue
        print(f"\n=== {proj}")
        subprocess.run(["crab", "status", "-d", full])
