"""
Builds a condor job area for the ntupleSelection stage.
"""

# Import Block

## Standard Python imports
import json
import os
import stat
import tarfile

## Kamui modules
from ..configReaders.sites import loadSites
from ..foundations import paths
from ..submit.common import checkTaskName, chunk, runTool

## Input files per job when the flag does not say otherwise
DEFAULT_FILES_PER_JOB = 5

RUN_SCRIPT = '#!/bin/bash\n# Generated by kamui. $1 = sample name, $2 = job index\nset -e\nSAMPLE=$1\nIDX=$2\necho "[job] sample=$SAMPLE index=$IDX host=$(hostname) start=$(date)"\n\nexport SCRAM_ARCH={scramArch}\nsource /cvmfs/cms.cern.ch/cmsset_default.sh\nscramv1 project CMSSW {cmsswVersion} > /dev/null\ncd {cmsswVersion}/src\neval `scramv1 runtime -sh`\ncd $_CONDOR_SCRATCH_DIR\n\ntar xzf kamuiPackage.tar.gz\nexport PYTHONPATH=$_CONDOR_SCRATCH_DIR/python:$PYTHONPATH\n\npython3 -c "import json; files=json.load(open(\'fileLists.json\'))[\'$SAMPLE\'][int(\'$IDX\')]; open(\'inputs.txt\',\'w\').write(chr(10).join(files))"\n\nmapfile -t INPUTS < inputs.txt\npython3 -m kamui.select.runOne {selectionJson} out.root "${{INPUTS[@]}}"\n\nxrdfs {eosRedirector} mkdir -p {outDir}\nxrdcp -f out.root {eosRedirector}/{outDir}/${{SAMPLE}}_selected_${{IDX}}.root\nxrdcp -f out.root.cutflow.json {eosRedirector}/{outDir}/${{SAMPLE}}_cutflow_${{IDX}}.json\necho "[job] end=$(date)"\n'

JDL = '# Generated by kamui - resubmit with: condor_submit {jdlName}\nuniverse                = vanilla\nexecutable              = $(script)\narguments               = $(sample) $(index)\ntransfer_input_files    = {inputFiles}\nshould_transfer_files   = YES\nwhen_to_transfer_output = ON_EXIT\noutput                  = logs/$(sample)_$(index).out\nerror                   = logs/$(sample)_$(index).err\nlog                     = logs/condor.log\nrequest_memory          = {memoryMB}\nrequest_disk            = {diskMB}\n# LPC worker OS selection. If jobs sit idle forever, try +REQUIRED_OS = "rhel9" instead.\n+DesiredOS              = "EL9"\nx509userproxy           = $ENV(X509_USER_PROXY)\n\nqueue sample,index,script from jobList.txt\n'


def taskDir(taskName, create=True):
    """The job area for a selection task."""
    checkTaskName(taskName)
    d = os.path.join(paths.SELECTION_JOBS_DIR, taskName)
    if create:
        os.makedirs(d, exist_ok=True)
    return d


def _scriptName(selectionName, era):
    return "runSelect_%s_%s.sh" % (selectionName, era)


def packageKamui(d):
    """Ship the kamui package so the worker can import it without a checkout."""
    out = os.path.join(d, "kamuiPackage.tar.gz")
    pkg = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    with tarfile.open(out, "w:gz") as tar:
        tar.add(pkg, arcname=os.path.join("python", "kamui"),
                filter=lambda ti: None if "__pycache__" in ti.name else ti)
    return out


def prepare(samples, taskName, fileLists, resolvedSelections, sites=None, filesPerJob=None,
            memoryMB=2000, diskMB=4000000, base=None, cmsswVersion=None, scramArch=None):
    """Write a complete condor area for a selection pass. Returns the directory and the job count."""
    sites = sites or loadSites()
    base = (base or sites["stageoutBase"]).rstrip("/")
    cmsswVersion = cmsswVersion or sites["cmssw"]["version"]
    scramArch = scramArch or sites["cmssw"]["scramArch"]

    d = taskDir(taskName)
    os.makedirs(os.path.join(d, "logs"), exist_ok=True)

    ## One resolved selection per era, since thresholds differ by era
    selectionFiles = {}
    for era in resolvedSelections:
        p = os.path.join(d, "selection_%s.json" % era)
        with open(p, "w") as f:
            json.dump(resolvedSelections[era], f, indent=2)
        selectionFiles[era] = p

    chunked, jobRows = {}, []
    for s in samples:
        lfns = fileLists.get(s["name"], [])
        if not lfns:
            continue
        groups = chunk(sorted(set(lfns)), int(filesPerJob or DEFAULT_FILES_PER_JOB))
        chunked[s["name"]] = groups
        script = _scriptName(resolvedSelections[s["era"]]["name"], s["era"])
        jobRows += ["%s,%d,%s" % (s["name"], i, script) for i in range(len(groups))]

    with open(os.path.join(d, "fileLists.json"), "w") as f:
        json.dump(chunked, f, indent=1)
    with open(os.path.join(d, "jobList.txt"), "w") as f:
        f.write(chr(10).join(jobRows) + chr(10))

    packageKamui(d)

    for era in selectionFiles:
        script = RUN_SCRIPT.format(
            scramArch=scramArch,
            cmsswVersion=cmsswVersion,
            selectionJson=os.path.basename(selectionFiles[era]),
            eosRedirector=sites["eosRedirector"].rstrip("/"),
            outDir="/".join([base, "selected", taskName, "$SAMPLE"]),
        )
        p = os.path.join(d, _scriptName(resolvedSelections[era]["name"], era))
        with open(p, "w") as f:
            f.write(script)
        os.chmod(p, os.stat(p).st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)

    inputFiles = ["fileLists.json", "kamuiPackage.tar.gz"] + [os.path.basename(selectionFiles[e]) for e in sorted(selectionFiles)]
    jdlName = "submit.jdl"
    with open(os.path.join(d, jdlName), "w") as f:
        f.write(JDL.format(jdlName=jdlName, inputFiles=",".join(inputFiles), memoryMB=memoryMB, diskMB=diskMB))

    record = {
        "task": taskName, "stage": "select", "nJobs": len(jobRows),
        "samples": sorted(chunked), "outDirBase": "/".join([base, "selected", taskName]),
        "selections": dict((era, resolvedSelections[era]["name"]) for era in resolvedSelections),
    }
    with open(os.path.join(d, "task.json"), "w") as f:
        json.dump(record, f, indent=2)

    return d, len(jobRows)


def submit(taskName, dryRun=False):
    """Run condor_submit on a selection job area."""
    d = taskDir(taskName, create=False)
    if dryRun:
        print("  [dryRun] condor_submit %s" % os.path.join(d, "submit.jdl"))
        return 0
    r = runTool(["condor_submit", "submit.jdl"], cwd=d, capture_output=True, text=True)
    print(r.stdout.strip() or r.stderr.strip())
    return r.returncode
